export const AL_ERROR_CODE = {
  HANDLE_DIRECTORY_CODE: 1,
  HANDLE_FILE_CODE: 2,
  HANDLE_SUBMIT_CODE: 3,
  HANDLE_EPISODES_LIST_CODE: 4,
  HANDLE_STORAGE_CODE: 5,
  GET_DIRECTORY_CODE: 6,
  GET_FILE_CODE: 7,
  GET_EPISODES_CODE: 8,
  SET_STORAGE_CODE: 9,
  GET_STORAGE_CODE: 10,
  EXECUTOR_CODE: 11,
};
